### ISSUE TITLE
I need filter the other pane text except the debug pane output windows.

### ISSUE THREAD

**Issue by lindexi** [nertilpoci/VisualStudio-Output-Filter-Extension#17]
Thx for @nertilpoci the tool is useful.

My VisualStudio will output some text in the output windows but some of them are like `Live Share` and `github for VisualStudio` and I do not want to view it.

**Comment by nertilpoci** [comment]
@lindexi  that's an excellent idea. Will look into adding an option to select output from different sources just like the output window has

**Comment by lindexi** [comment]
@nertilpoci I writing the code to get only the DEBUG windows and can I pull requests?

**Comment by nertilpoci** [comment]
Implemented in latest version
